// <auto-generated />
using AnimalWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalWebApi.Migrations
{
    [DbContext(typeof(AnimalDbContext))]
    [Migration("20220907134245_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnimalWebApi.Entities.Animal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Age = "10",
                            Breed = "Abyssinian",
                            Description = "The Abyssinian /æbɪˈsɪniən/ is a breed of domestic short-haired cat with a distinctive \"ticked\" tabby coat, in which individual hairs are banded with different colors.[2] They are also known simply as Abys.",
                            PetName = "Cat"
                        },
                        new
                        {
                            Id = "2",
                            Age = "13",
                            Breed = "Aegean",
                            Description = "Aegean cats (Greek: γάτα του Αιγαίου gáta tou Aigaíou) are a naturally occurring landrace of domestic cat originating from the Cycladic Islands of Greece and western Turkey. ",
                            PetName = "Cat"
                        },
                        new
                        {
                            Id = "3",
                            Age = "13",
                            Breed = "Aegean",
                            Description = "Aegean cats (Greek: γάτα του Αιγαίου gáta tou Aigaíou) are a naturally occurring landrace of domestic cat originating from the Cycladic Islands of Greece and western Turkey.",
                            PetName = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
